"""Data models for the Analyst Engine.

Trade candidates generated by autonomous market scanning.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional, Any
from enum import Enum

from pydantic import BaseModel, Field


class SetupType(str, Enum):
    """Types of trade setups the analyst can detect."""
    EMA_PULLBACK = "EMA_PULLBACK"
    EMA_BREAKOUT = "EMA_BREAKOUT"
    RANGE_PLAY = "RANGE_PLAY"
    MOMENTUM_BURST = "MOMENTUM_BURST"
    VOLUME_SPIKE = "VOLUME_SPIKE"
    SUPPORT_BOUNCE = "SUPPORT_BOUNCE"
    RESISTANCE_REJECT = "RESISTANCE_REJECT"
    TREND_CONTINUATION = "TREND_CONTINUATION"
    UNKNOWN = "UNKNOWN"


class IndicatorSnapshot(BaseModel):
    """Technical indicator values at analysis time."""
    ema_8: Optional[float] = None
    ema_21: Optional[float] = None
    ema_50: Optional[float] = None
    ema_200: Optional[float] = None
    rsi_14: Optional[float] = None
    rsi_7: Optional[float] = None
    atr_14: Optional[float] = None
    volume_sma_ratio: Optional[float] = None  # Current vol / 20-period SMA
    bb_upper: Optional[float] = None
    bb_lower: Optional[float] = None
    bb_width: Optional[float] = None
    macd_line: Optional[float] = None
    macd_signal: Optional[float] = None
    macd_histogram: Optional[float] = None
    adx: Optional[float] = None
    plus_di: Optional[float] = None
    minus_di: Optional[float] = None
    funding_rate: Optional[float] = None
    open_interest_change: Optional[float] = None


class TradeCandidate(BaseModel):
    """A trade setup detected by the analyst.

    Converts directly to a Signal for the existing pipeline.
    """
    candidate_id: str = Field(default_factory=lambda: f"analyst-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}-{id(object())}")
    symbol: str
    setup_type: SetupType
    side: str  # LONG or SHORT
    entry: float
    stop_loss: float
    take_profit: float
    leverage: int = Field(default=10, ge=1, le=125)
    margin_mode: str = "ISOLATED"
    confidence: float = Field(..., ge=0, le=100)  # Analyst's confidence 0-100

    # Analysis context
    indicators: IndicatorSnapshot = Field(default_factory=IndicatorSnapshot)
    regime: str = "UNKNOWN"
    timeframe: str = "1H"  # Which timeframe was analyzed

    # Reasoning
    thesis: str = ""  # Why this setup
    risk_reward: Optional[float] = None  # Calculated R:R
    expected_duration_minutes: Optional[int] = None

    # Metadata
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    analyst_version: str = "1.0"

    def to_signal(self) -> dict[str, Any]:
        """Convert to a Signal-compatible dict for the parser pipeline."""
        return {
            "source": "analyst",
            "raw_text": f"ANALYST {self.side} {self.symbol} @ {self.entry} SL {self.stop_loss} TP {self.take_profit} ({self.setup_type.value})",
            "symbol": self.symbol,
            "side": self.side,
            "entry": self.entry,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "leverage": self.leverage,
            "margin_mode": self.margin_mode,
            "confidence": self.confidence,
            "metadata": {
                "setup_type": self.setup_type.value,
                "regime": self.regime,
                "timeframe": self.timeframe,
                "thesis": self.thesis,
                "risk_reward": self.risk_reward,
                "indicators": self.indicators.model_dump(),
            }
        }


class ScanResult(BaseModel):
    """Result of scanning a single symbol."""
    symbol: str
    scanned_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    candidates: list[TradeCandidate] = Field(default_factory=list)
    regime: str = "UNKNOWN"
    error: Optional[str] = None

    @property
    def has_candidates(self) -> bool:
        return len(self.candidates) > 0


class MarketScan(BaseModel):
    """Result of scanning multiple symbols."""
    scan_id: str = Field(default_factory=lambda: f"scan-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}")
    symbols_scanned: int = 0
    symbols_with_candidates: int = 0
    total_candidates: int = 0
    results: list[ScanResult] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: Optional[datetime] = None

    def finalize(self) -> None:
        """Compute summary statistics."""
        self.completed_at = datetime.now(timezone.utc)
        self.symbols_scanned = len(self.results)
        self.symbols_with_candidates = sum(1 for r in self.results if r.has_candidates)
        self.total_candidates = sum(len(r.candidates) for r in self.results)
